#!/bin/bash

declare -A files
IFS=$'\n' read -d '' -r -a arr < <(find /home/rhett/books -type f)

for i in "${arr[@]}"; do
    base=$(basename "$i")
    files["$base"]="$i"
done

choice=$(printf "%s\n" "${!files[@]}" | dmenu -i -l 25)

if [ -n "$choice" ]; then
    xdg-open "${files["$choice"]}"
fi

