#!/usr/bin/python3

import os
import filecmp
import shutil
import sys

ascii = """

# ================================================================== #
#                                   db                               #
#                                                                    #
#                ,p6"bo   ,6"Yb.  `7MM  `7MMpMMMb.                   #
#               6M'  OO  8)   MM    MM    MM    MM                   #
#               8M        ,pm9MM    MM    MM    MM                   #
#               YM.    , 8M   MM    MM    MM    MM                   #
#                YMbmd'  `Moo9^Yo..JMML..JMML  JMML.                 #
#                                                                    #
# ================================================================== #
#       This Program Was Made April 2025 By Rhett Applestone         #
#                                                                    #
#                            MIT License                             #
#                Copyright (c) 2025 Rhett Applestone                 #
# ================================================================== #

"""

# All files that need to be tracked

filesToTrack = [
    "bashrc",
    "microBindings",
    "microSettings",
    "inputRemapperConfig",
    "inputRemapperXmodmap",
    "inputRemapperBindingsAT",
    "inputRemapperBindingsCOOLER",
    "cinnamonSettings",
    "cinnamonMenuSettings"
]

    
# location of all filesToTrack on system in a dictionary
systemPaths = {
    "bashrc": "../.bashrc",
    "microBindings": "../.config/micro/bindings.json",
    "microSettings": "../.config/micro/settings.json",
    "inputRemapperConfig": "../.config/input-remapper-2/config.json",
    "inputRemapperXmodmap": "../.config/input-remapper-2/xmodmap.json",
    "inputRemapperBindingsAT": "../.config/input-remapper-2/presets/AT Translated Set 2 keyboard/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "../.config/input-remapper-2/presets/COOLER MASTER SK620 Mechanical Keyboard - Black Edition/rhett-keybindingsCOOLER.json",
    "cinnamonSettings": "./files/system-cinnamon",
    "cinnamonMenuSettings": "../.config/cinnamon/spices/menu@cinnamon.org/0.json"
}

# location of all filesToTrack (stored in cain's filesToTrack dir) in a dictionary
programPaths = {
    "bashrc": "./files/dotfiles/.bashrc",
    "microBindings": "./files/micro/bindings.json",
    "microSettings": "./files/micro/settings.json",
    "inputRemapperConfig": "./files/input-remapper/config.json",
    "inputRemapperXmodmap": "./files/input-remapper/xmodmap.json",
    "inputRemapperBindingsAT": "./files/input-remapper/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "./files/input-remapper/rhett-keybindingsCOOLER.json",
    "cinnamonSettings": "./files/cinnamon/cinnamon-settings",
    "cinnamonMenuSettings": "./files/cinnamon/0.json"
}


# programs to install
programsToInstall = [
	"micro",
	"xclip",
	"input-remapper",
	"git",
	"virtualbox",
	"inkscape",
	"hexcurse"
]

#function to check if two filesToTrack have any differences

def filesAreDifferent(file1, file2):
    if(not(filecmp.cmp(file1, file2, shallow=False))):
        return True
    else:
        return False

#strips filename from the end of path
def stripFileName(path):
    index = path.rfind("/")
    return path[:index+1]
    

def collect():
    # variable to keep track of what if any filesToTrack have changed since the program has run last
    allFilesChanged = ""
    #dconf dumping all system settings to a temporary file
    os.system("dconf dump / > ~/cain/files/system-cinnamon")
    
    # main program
    print("Files Changed:")
    
    for file in filesToTrack:
        if filesAreDifferent(systemPaths[file], programPaths[file]):
            shutil.copy(systemPaths[file], programPaths[file])
            allFilesChanged = allFilesChanged + " " + file
            print("    CHANGED: " + file)
        else:
            print("    SAME: " + file)

    # clean up tmp file
    os.system("rm ~/cain/files/system-cinnamon")

    if (allFilesChanged != ""):
        os.system("cd ~/cain && git add . && git commit -m \"CHANGED: " + allFilesChanged +"\" && git push")
    else:
        print("\nALL FILES ARE THE SAME\n")


def install():
    print("INSTALLING:")
    os.system("sudo apt update")
    
    #install all programs listed in programToInstall array
    for program in programsToInstall:
    	os.system("sudo apt install " + program + " -y")
    
    #configure git
    os.system("git config --global user.name \"Rhett Applestone\"")
    os.system("git config --global user.email \"rhettapples(at symbol)gmail.com\"")

    #check if dirs exist, and make them if they don't
    #put every file into it's place

    #making special dirs for input remapper
    os.system("mkdir ../.config/input-remapper-2/")
    os.system("mkdir ../.config/input-remapper-2/presets/")
    
    for file in filesToTrack:
        if(not(os.path.isdir(stripFileName(systemPaths[file])))):
            os.mkdir(stripFileName(systemPaths[file]))

    for file in filesToTrack:
        if (file != "cinnamonSettings"):
            shutil.copy(programPaths[file], systemPaths[file])
        else:
            os.system("dconf load / < ~/cain/files/cinnamon/cinnamon-settings")

    os.system("reboot")


def select():
    if len(sys.argv) < 2:
        choice = input("Would you Like to Collect (C) or install (I)?: ")
        if (choice == "I" or choice == "i"):
            install()
        elif (choice == "C" or choice == "c"):
            collect()
        else:
            print("\nNon valid input, please try again\n")
            select()
    elif sys.argv[1] == "-c" or sys.argv[1] == "-C":
        collect()
    elif sys.argv[1] == "-i" or sys.argv[1] == "-I":
        install()
    else:
        print("\nNon valid input, please try again\n")
        select()

    
#main program that executes
print(ascii)
select()
