#!/bin/bash

# ================================================================== #
#                                   db                               #
#                                                                    #
#                ,p6"bo   ,6"Yb.  `7MM  `7MMpMMMb.                   #
#               6M'  OO  8)   MM    MM    MM    MM                   #
#               8M        ,pm9MM    MM    MM    MM                   #
#               YM.    , 8M   MM    MM    MM    MM                   #
#                YMbmd'  `Moo9^Yo..JMML..JMML  JMML.                 #
#                                                                    #
# ================================================================== #
#     This Program Was Made January 2025 By Rhett Applestone         #
#                                                                    #
#                            MIT License                             #
#                Copyright (c) 2025 Rhett Applestone                 #
# ================================================================== #




# ================================================================== #
cat files/cai


#save rc to dotfiles in collected files
cp ~/.bashrc ~/cain/files/dotfiles
if [ $? -eq 0 ]; then
	echo ".bashrc collected"
fi


dconf dump / > ~/cain/files/cinnamon/cinnamon-settings
if [ $? -eq 0 ]; then
	echo "cinnamon settings "
fi


cp ~/.config/input-remapper-2/presets/AT\ Translated\ Set\ 2\ keyboard/rhett-keybindings.json ~/cain/files/input-remapper

cp ~/.config/input-remapper-2/config.json ~/cain/files/input-remapper

cp ~/.config/micro/bindings.json ~/cain/files/micro

# ================================================================== #
