#!/bin/bash

# ================================================================== #
#                                   db                               #
#                                                                    #
#                ,p6"bo   ,6"Yb.  `7MM  `7MMpMMMb.                   #
#               6M'  OO  8)   MM    MM    MM    MM                   #
#               8M        ,pm9MM    MM    MM    MM                   #
#               YM.    , 8M   MM    MM    MM    MM                   #
#                YMbmd'  `Moo9^Yo..JMML..JMML  JMML.                 #
#                                                                    #
# ================================================================== #
#       This Program Was Made April 2025 By Rhett Applestone         #
#                                                                    #
#                            MIT License                             #
#                Copyright (c) 2025 Rhett Applestone                 #
# ================================================================== #


# ==================== Error handling function ===================== #

handle_error () {
	echo "An error has occured" && exit 1 
}

# ================== Making The CLI look pretty ==================== #

# Printing cain ascii art to terminal
cat ~/cain/files/cainfiles/cai || handle_error

# ================== Installing Needed Programs ==================== #

# Update to most reecent apt repos
sudo apt update -y || handle_error

# Text editor I use
sudo apt install micro -y || handle_error

# Getting clipboard working right
sudo apt install xclip -y || handle_error

# Getting program I use for keybindings
sudo apt install input-remapper -y || handle_error



# Getting background I like (optional)

# Installing git and configuring it
sudo apt install git -y || handle_error
git config --global user.name "Rhett Applestone" || handle_error
git config --global user.email "rhettapples(at symbol)gmail.com" || handle_error

# ================ Putting Files In The Right Places =============== #


# Loading configs for cinnamon desktop enviornment
dconf load / < ~/cain/files/cinnamon/cinnamon-settings || handle_error

# Loading configs for cinnamon menu settings
cp ~/cain/files/cinnamon/0.json ~/.config/cinnamon/spices/menu@cinnamon.org/ || handle_error

# Making a directory to put micro bindings in if they don't exist
if [ ! -d "$HOME/.config/micro" ]; then
  mkdir ~/.config/micro || handle_error
fi

if [ ! -d "$HOME/.config/micro/buffers" ]; then
  mkdir ~/.config/micro/buffers || handle_error
fi

# Loading micro keybindings
cp ~/cain/files/micro/bindings.json ~/.config/micro/ || handle_error

# Loading micro settings
cp ~/cain/files/micro/settings.json ~/.config/micro/ || handle_error


#Making correct directories for input-remapper if they don't exist
if [ ! -d "$HOME/.config/input-remapper-2" ]; then
  mkdir ~/.config/input-remapper-2 || handle_error
fi

if [ ! -d "$HOME/.config/input-remapper-2/presets" ]; then
  mkdir ~/.config/input-remapper-2/presets || handle_error
fi

if [ ! -d "$HOME/.config/input-remapper-2/presets/AT\ Translated\ Set\ 2\ keyboard" ]; then
  mkdir ~/.config/input-remapper-2/presets/AT\ Translated\ Set\ 2\ keyboard || handle_error
fi

if [ ! -d "$HOME/.config/input-remapper-2/presets/COOLER\ MASTER\ SK620\ Mechanical\ Keyboard\ -\ Black\ Edition" ]; then
  mkdir ~/.config/input-remapper-2/presets/COOLER\ MASTER\ SK620\ Mechanical\ Keyboard\ -\ Black\ Edition || handle_error
fi


# Loading keybindings for input-remapper
cp ~/cain/files/input-remapper/rhett-keybindings.json ~/.config/input-remapper-2/presets/AT\ Translated\ Set\ 2\ keyboard/ || handle_error
cp ~/cain/files/input-remapper/rhett-keybindings.json ~/.config/input-remapper-2/COOLER\ MASTER\ SK620\ Mechanical\ Keyboard\ -\ Black\ Edition/ || handle_error

# Loading config file for input-remapper
cp ~/cain/files/input-remapper/config.json ~/.config/input-remapper-2/ || handle_error

# Loading xmodmap for input-remapper
cp ~/cain/files/input-remapper/xmodmap.json ~/.config/input-remapper-2/  || handle_error

# Starting and auto loading input-remapper and keybindings
sudo input-remapper-control --command autoload || handle_error

# Loading my .bashrc file
cp ~/cain/files/dotfiles/.bashrc ~/ || handle_error

# Copying cain to the user's $PATH so it can be executed
sudo cp cain /usr/local/bin/ || handle_error


# Successful install of cain
echo -e "\ncain is installed"

# Countdown before restart
echo -e "reboot in:"	
for i in $(seq 0 4);
do	
	echo "$((5 - i))"
    sleep 1    
done

reboot

# ================================================================== #

