#!/usr/bin/python3
import os

programsToInstall = [
	"micro",
	"xclip",
	"input-remapper",
	"git"
	"virtualbox"
]

files = [
    "bashrc",
    "microBindings",
    "microSettings",
    "inputRemapperBindingsAT",
    "inputRemapperBindingsCOOLER",
    "inputRemapperConfig",
    "inputRemapperXmodmap",
    "cinnamonSettings",
    "cinnamonMenuSettings"
]

# location of all files on system in a dictionary
systemPath = {
    "bashrc": "$HOME/.bashrc",
    "microBindings": "$HOME/.config/micro/bindings.json",
    "microSettings": "$HOME/.config/micro/settings.json",
    "inputRemapperBindingsAT": "$HOME/.config/input-remapper-2/presets/AT Translated Set 2 keyboard/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "$HOME/.config/input-remapper-2/presets/COOLER MASTER SK620 Mechanical Keyboard - Black Edition/rhett-keybindingsCOOLER.json",
    "inputRemapperConfig": "$HOME/.config/input-remapper-2/config.json",
    "inputRemapperXmodmap": "$HOME/.config/input-remapper-2/xmodmap.json",
    "cinnamonSettings": "./files/tmp/system-cinnamon",
    "cinnamonMenuSettings": "$HOME/.config/cinnamon/spices/menu@cinnamon.org/0.json"
}

# location of all files (stored in cain's files dir) in a dictionary
programPath = {
    "bashrc": "./files/dotfiles/.bashrc",
    "microBindings": "./files/micro/bindings.json",
    "microSettings": "./files/micro/settings.json",
    "inputRemapperBindingsAT": "./files/input-remapper/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "./files/input-remapper/rhett-keybindingsCOOLER.json",
    "inputRemapperConfig": "./files/input-remapper/config.json",
    "inputRemapperXmodmap": "./files/input-remapper/xmodmap.json",
    "cinnamonSettings": "./files/cinnamon/cinnamon-settings",
    "cinnamonMenuSettings": "./files/cinnamon/0.json"
}


os.system("sudo apt update")


#install all programs listed in programToInstall array
for program in programsToInstall:
	os.system("sudo apt install " + program + " -y")

#configure git
os.system("git config --global user.name \"Rhett Applestone\"")
os.system("git config --global user.email \"rhettapples(at symbol)gmail.com\"")


# for every dir in system path
# check if dir exists
#if dir doesnot exists, make the dir

#for every file in 
