#!/bin/bash

# ================================================================== #
#                                   db                               #
#                                                                    #
#                ,p6"bo   ,6"Yb.  `7MM  `7MMpMMMb.                   #
#               6M'  OO  8)   MM    MM    MM    MM                   #
#               8M        ,pm9MM    MM    MM    MM                   #
#               YM.    , 8M   MM    MM    MM    MM                   #
#                YMbmd'  `Moo9^Yo..JMML..JMML  JMML.                 #
#                                                                    #
# ================================================================== #
#     This Program Was Made January 2025 By Rhett Applestone         #
#                                                                    #
#                            MIT License                             #
#                Copyright (c) 2025 Rhett Applestone                 #
# ================================================================== #


# ================== Installing Needed Programs ==================== #

# Update to most reecent apt repos
sudo apt update -y

# Text editor I use
sudo apt install micro -y

# Getting clipboard working right
sudo apt install xclip -y

# Getting program I use for keybindings
sudo apt install input-remapper -y

# Getting background I like
sudo apt install mint-backgrounds-victoria -y


# ================ Putting Files In The Right Places =============== #

# Loading configs for cinnamon desktop enviornment
dconf load / < ~/cain/files/cinnamon/cinnamon-settings

# Loading keybindings for input-remapper
cp ~/cain/files/input-remapper/rhett-keybindings.json ~/.config/input-remapper-2/presets/AT\ Translated\ Set\ 2\ keyboard

# Loading config file for input-remapper
cp ~/cain/files/input-remapper/config.json ~/.config/input-remapper-2

# Starting input reamapper
input-remapper-control --command autoload

# Loading my .bashrc file
cp ~/cain/files/dotfiles/.bashrc ~

# Making bash see the new .bashrc file
source ~/.bashrc

# Loading micro keybindings
cp ~/cain/files/micro/bindings.json ~/.config/micro

sudo cp cain /usr/local/bin

# ================================================================== #

