#!/usr/bin/python3

import os
import filecmp
import shutil

ascii = """

# ================================================================== #
#                                   db                               #
#                                                                    #
#                ,p6"bo   ,6"Yb.  `7MM  `7MMpMMMb.                   #
#               6M'  OO  8)   MM    MM    MM    MM                   #
#               8M        ,pm9MM    MM    MM    MM                   #
#               YM.    , 8M   MM    MM    MM    MM                   #
#                YMbmd'  `Moo9^Yo..JMML..JMML  JMML.                 #
#                                                                    #
# ================================================================== #
#       This Program Was Made April 2025 By Rhett Applestone         #
#                                                                    #
#                            MIT License                             #
#                Copyright (c) 2025 Rhett Applestone                 #
# ================================================================== #

"""

# All files that need to be tracked

files = [
    "bashrc",
    "microBindings",
    "microSettings",
    "inputRemapperBindingsAT",
    "inputRemapperBindingsCOOLER",
    "inputRemapperConfig",
    "inputRemapperXmodmap",
    "cinnamonSettings",
    "cinnamonMenuSettings"
]

# location of all files on system in a dictionary
systemPath = {
    "bashrc": "../.bashrc",
    "microBindings": "../.config/micro/bindings.json",
    "microSettings": "../.config/micro/settings.json",
    "inputRemapperBindingsAT": "../.config/input-remapper-2/presets/AT Translated Set 2 keyboard/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "../.config/input-remapper-2/presets/COOLER MASTER SK620 Mechanical Keyboard - Black Edition/rhett-keybindingsCOOLER.json",
    "inputRemapperConfig": "../.config/input-remapper-2/config.json",
    "inputRemapperXmodmap": "../.config/input-remapper-2/xmodmap.json",
    "cinnamonSettings": "./files/tmp/system-cinnamon",
    "cinnamonMenuSettings": "../.config/cinnamon/spices/menu@cinnamon.org/0.json"
}

# location of all files (stored in cain's files dir) in a dictionary
programPath = {
    "bashrc": "./files/dotfiles/.bashrc",
    "microBindings": "./files/micro/bindings.json",
    "microSettings": "./files/micro/settings.json",
    "inputRemapperBindingsAT": "./files/input-remapper/rhett-keybindingsAT.json",
    "inputRemapperBindingsCOOLER": "./files/input-remapper/rhett-keybindingsCOOLER.json",
    "inputRemapperConfig": "./files/input-remapper/config.json",
    "inputRemapperXmodmap": "./files/input-remapper/xmodmap.json",
    "cinnamonSettings": "./files/cinnamon/",
    "cinnamonMenuSettings": "./files/cinnamon/0.json"
}

# variable to keep track of what if any files have changed since the program has run last
allFilesChanged = ""


#function to check if two files have any differences

def filesAreDifferent(file1, file2):
    if(not(filecmp.cmp(file1, file2, shallow=False))):
        return True
    else:
        return False

#dconf dumping all system settings to a temporary file
os.system("dconf dump / > ~/cain/files/tmp/system-cinnamon")

# main program
print(ascii)
print("Files Changed:")

for file in files:
    if filesAreDifferent(programPath[file], systemPath[file]):
        shutil.copy(programPath[file], systemPath[file])
        allFilesChanged = allFilesChanged + " " + file
        print("    CHANGED: " + file)
    else:
        print("    SAME: " + file)



if (allFilesChanged != ""):
    os.system("cd ~/cain && git add . && git commit -m \"CHANGED: " + allFilesChanged +"\" && git push")
        
# clean up tmp file
os.system("rm ~/cain/files/tmp/system-cinnamon")


